### ISSUE TITLE
Comment from Lesson 9

### ISSUE THREAD

**Issue by katilp** [awesome-workshop/intro-to-docker#4]
Continuing:

in 09-gitlab-ci
- [x] I do not quite get what I should remove for the image : "Now, remove the line `image: rootproject/root-conda` underneath the stages, since the image-building stage uses its own dedicated image for automated image building (see callout below). You’ll then need to explicitly specify that the other stages use this image by adding the line `image: rootproject/root-conda` to the stages, since it’s no longer a global specification." With a simple-minded read this says that I shoud remover rootproject/root-conda and the add it again, but I do suspect this is not the case. Note also that for now (from CI/CD) I have   image: rootproject/root-conda:6.18.04. You maybe mean removing that line from `.build_image`. It would be helpful to refer to the .gitlab_ci.yml as it comes out in https://awesome-workshop.github.io/continuous-integration-deployment-gitlab/14-plotting-to-take-over-the-world/index.html

**Comment by katilp** [comment]
- [x] the meaning of the last exercise is not quite clear. I've made a new skim_prebuilt.sh and pushed it to my repo. But I guess I'm should now use it somewhere, i.e. make changes to the Dockerfile to use it?

**Comment by danikam** [comment]
The confusion in the 09-gitlab-ci instruction was because you uncovered an inconsistency between the [.gitlab-ci.yml in Payload Stage 2 analysis](https://gitlab.cern.ch/awesome-workshop/awesome-analysis-eventselection-stage2/blob/master/.gitlab-ci.yml) and Giordon's implementation in the gitlab-ci tutorial. Thank you very much!! This drives home the point that this and any other such inconsistencies will need to be removed from these 'starter repos'

**Comment by danikam** [comment]
>     * [ ]  the meaning of the last exercise is not quite clear. I've made a new skim_prebuilt.sh and pushed it to my repo. But I guess I'm should now use it somewhere, i.e. make changes to the Dockerfile to use it?

There shouldn't be any need to edit the Dockerfile for this exercise, the idea is just to remove the building portion of the script since it's now already being done in the Dockerfile. The script will be used in the final exercise in the next episode (a.k.a lesson) when we go through the full analysis in the gitlab-ci-created containers. I'll add a comment to try and make it more clear why we're doing this.

**Comment by danikam** [comment]
Comment added :)
